### ISSUE TITLE
RSS epoch needs to be updated

### ISSUE THREAD

**Issue by Arrowstar** [KSPtoMars/KSPtoMarsTools#12]
The epoch in the RSS Kopernicus config file is wrong and needs to be updated to that shown in the mod changes required Google Drive document.

**Comment by darko-pilav** [comment]
This requires a change in a cfg file.

We will copy the relevant config file, make the change, upload the modified config to ksptomars.org and fetch it from there. We can do that as soon as Orkeren comes back.

Thanks for calling attention to it!

**Comment by frenzeldk** [comment]
why don't we just add the config file to [KSPtoMarsMod](https://github.com/KSPtoMars/KSPtoMarsMod)?

**Comment by darko-pilav** [comment]
we could do that .. I just wanted to keep it consistent because we are fetching other things from ksptomars.org.
Do you want me to do that?

**Comment by frenzeldk** [comment]
@darko-pilav, there shouldn't be a lot that we fetch from ksptomars.org by now. And yes, please add it to the mod.

**Comment by darko-pilav** [comment]
Hey @Arrowstar,

As soon as i change the epoch in the RSS Kopernicus config file  to **Epoch = -2524614641.784** KSP won't let me start a new game or resume an old one. The buttons in the Menu just don't work

Is this something you've already encountered? Any ideas how to fix this?

Cheers

**Comment by Arrowstar** [comment]
Hey there, Arrowstar here. I've encountered it before but I thought it was
fixed?  It works for me anyway. I would talk to Nathan Kell and have him
look into it.

Arrowstar
