### ISSUE TITLE
need new parts from RKE Kanadarm

### ISSUE THREAD

**Issue by danielskoenig** [KSPtoMars/KSPtoMarsTools#18]
I need 2 parts from the RKE Kanadarm mod, the LEE and PDGF. The two parts are named "rkeklee" and "rkekpdgf"

Link to Kerbalstuff: https://kerbalstuff.com/mod/637/RKE%20Kanadarm

**Comment by frenzeldk** [comment]
closed with 636eca36ab92027a9ab40e7e4290f2528c8ba799

**Comment by frenzeldk** [comment]
Part removal not done yet
