### ISSUE TITLE
4.0.7-beta windows amd64 crash on install

### ISSUE THREAD

**Issue by space-is-hard** [KSPtoMars/KSPtoMarsTools#7]
![2marsinstcrash](https://cloud.githubusercontent.com/assets/10237092/8788549/34b8b9f8-2f09-11e5-9537-e251133b3738.png)

**Comment by frenzeldk** [comment]
Windows has a path-limit of 255 characters.

**Comment by space-is-hard** [comment]
Is there no solution to this?

**Comment by darko-pilav** [comment]
There are some somewhat cumbersome solutions but I would suggest you copy/move your KSP folder to somewhere where the path is shorter.

Alternatively you could use the "subst" command in cmd to substitute a path with a drive letter (as can be seen [here](http://support.code42.com/CrashPlan/Latest/Troubleshooting/Windows_File_Paths_Longer_Than_255_Characters)).

i.e.
"subst Y: C:\Example\File\Path"

and use the substituted drive letter.

**Comment by space-is-hard** [comment]
`subst` was successful and very easy, thank you.

**Comment by frenzeldk** [comment]
@space-is-hard may I ask, why you are in need of such long file paths?

**Comment by space-is-hard** [comment]
Mostly because I've got multiple KSP installs of various versions that I'm trying to keep semi-organized
